"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.2.
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# ============================================
# PATHS & ENV LOADING
# ============================================
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path)
else:
    load_dotenv(BASE_DIR.parent / '.env')


def env_bool(key: str, default: bool = False) -> bool:
    return os.getenv(key, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(key: str, default: str = '') -> list[str]:
    raw = os.getenv(key, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# ============================================
# CORE SECURITY
# ============================================
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-@e2&yg!lk#5aj&yvs-&%%-%@=t90rvn)+y@u*6bdebh7a^et))'
)

DEBUG = env_bool('DEBUG', False)

# En producción exigimos SECRET_KEY explícita (no fallback inseguro)
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise RuntimeError(
        'SECRET_KEY inseguro detectado en producción. Configura SECRET_KEY en .env'
    )

DOMAIN = os.getenv('DOMAIN', '127.0.0.1:8000')
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1' if not DEBUG else '*')

# Guardia: no permitir ALLOWED_HOSTS='*' en producción
if not DEBUG and ('*' in ALLOWED_HOSTS or not ALLOWED_HOSTS):
    raise RuntimeError(
        "ALLOWED_HOSTS no puede ser '*' o vacío en producción. "
        "Configura ALLOWED_HOSTS en .env con dominios explícitos."
    )

# Add apps directory to PYTHONPATH
sys.path.append(os.path.join(BASE_DIR, 'apps'))


# ============================================
# APPLICATIONS
# ============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    'axes',
    'dbbackup',

    # Local apps
    'apps.platform',
    'apps.internal',
    'apps.labs',
    'apps.secretary_doc',
    'apps.notifications',
    'apps.audit',
    'apps.documents',
    'apps.settings_runtime',
]


# ============================================
# MIDDLEWARE
# ============================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Axes (brute-force protection) - MUST be last auth middleware
    'axes.middleware.AxesMiddleware',
    # Audit trail middleware (captures request context for signals)
    'apps.audit.middleware.AuditContextMiddleware',
]


# ============================================
# DRF
# ============================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_ANON', '30/min'),
        'user': os.getenv('THROTTLE_USER', '120/min'),
        'login': os.getenv('THROTTLE_LOGIN', '5/min'),
        'register': os.getenv('THROTTLE_REGISTER', '10/hour'),
        'password_reset': os.getenv('THROTTLE_PASSWORD_RESET', '5/hour'),
        'public_tracking': os.getenv('THROTTLE_PUBLIC_TRACKING', '20/min'),
    },
}


# ============================================
# JWT
# ============================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', '60'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', '7'))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


# ============================================
# CORS
# ============================================
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173'
)
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', True)
# En producción NUNCA permitir todos los orígenes
CORS_ALLOW_ALL_ORIGINS = DEBUG and env_bool('CORS_ALLOW_ALL_ORIGINS', True)


# ============================================
# SPECTACULAR (minified)
# ============================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'TUho API - Sistema Integral Universitario',
    'DESCRIPTION': 'API para la aplicación TUho - Sistema Integral de Gestión Universitaria',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {
        'name': 'Equipo de Desarrollo TUho',
        'email': os.getenv('SUPPORT_EMAIL', 'soporte@uho.edu.cu'),
        'url': 'https://www.uho.edu.cu'
    },
    'COMPONENT_SPLIT_REQUEST': False,
    'SORT_OPERATIONS': False,
}


# ============================================
# ROUTING / TEMPLATES
# ============================================
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates", "templates/"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context.groups_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ============================================
# DATABASE
# ============================================
if os.getenv('DATABASE_ENGINE') == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DATABASE_NAME', 'tuho_db'),
            'USER': os.getenv('DATABASE_USER', 'tuho_user'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
            'HOST': os.getenv('DATABASE_HOST', 'localhost'),
            'PORT': os.getenv('DATABASE_PORT', '5432'),
            'CONN_MAX_AGE': int(os.getenv('DATABASE_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ============================================
# PASSWORD VALIDATION (endurecida)
# ============================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': int(os.getenv('PASSWORD_MIN_LENGTH', '8'))},
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ============================================
# I18N
# ============================================
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'Cuba'
USE_I18N = True
USE_TZ = True


# ============================================
# STATIC / MEDIA
# ============================================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'Login'


# ============================================
# EMAIL
# ============================================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', True)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@uho.edu.cu')
ALLOWED_REDIRECT_URLS = ['mailto://']

# En desarrollo, si no hay credenciales SMTP reales, usar console backend
# para evitar errores de autenticación contra Gmail con placeholders.
_PLACEHOLDER_EMAIL_USERS = ('', 'tu_correo@uho.edu.cu', 'tu_correo@gmail.com')
if DEBUG and (EMAIL_HOST_USER in _PLACEHOLDER_EMAIL_USERS or not EMAIL_HOST_PASSWORD):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ============================================
# AUTH / USER MODEL
# ============================================
AUTH_USER_MODEL = 'platform.User'

AUTHENTICATION_BACKENDS = [
    # Axes debe ir primero
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# ============================================
# DJANGO-AXES (brute force protection)
# ============================================
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = timedelta(minutes=int(os.getenv('AXES_COOLOFF_MINUTES', '15')))
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ['ip_address', 'username']
AXES_ENABLED = env_bool('AXES_ENABLED', True)
AXES_LOCKOUT_CALLABLE = 'apps.platform.views.auth.axes_lockout_response'


# ============================================
# SECURITY HEADERS (producción)
# ============================================
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

# Activar solo en producción (requiere HTTPS)
if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    # El frontend usa JWT (no necesita leer el CSRF desde JS)
    CSRF_COOKIE_HTTPONLY = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
)


# ============================================
# CELERY (tareas asíncronas)
# ============================================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# Ejecutar tareas sincrónicamente si Celery no está disponible (desarrollo)
CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', DEBUG)
CELERY_TASK_EAGER_PROPAGATES = True


# ============================================
# DBBACKUP
# ============================================
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {
    'location': os.getenv('DBBACKUP_LOCATION', str(BASE_DIR / 'backups')),
}
DBBACKUP_FILENAME_TEMPLATE = 'tuho-{databasename}-{datetime}.{extension}'
DBBACKUP_MEDIA_FILENAME_TEMPLATE = 'tuho-media-{datetime}.{extension}'


# ============================================
# FILE UPLOAD LIMITS
# ============================================
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', str(10 * 1024 * 1024)))  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', str(10 * 1024 * 1024)))

# Tipos MIME permitidos para adjuntos generales
ALLOWED_UPLOAD_MIME_TYPES = env_list(
    'ALLOWED_UPLOAD_MIME_TYPES',
    'application/pdf,image/jpeg,image/png,image/webp,'
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document,'
    'application/msword,'
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,'
    'application/vnd.ms-excel'
)


# ============================================
# INSTITUCIONAL (para PDFs / emails)
# ============================================
INSTITUTION_NAME = os.getenv('INSTITUTION_NAME', 'Universidad de Holguín')
INSTITUTION_SHORT_NAME = os.getenv('INSTITUTION_SHORT_NAME', 'UHo')
INSTITUTION_ADDRESS = os.getenv('INSTITUTION_ADDRESS', 'Holguín, Cuba')
INSTITUTION_WEBSITE = os.getenv('INSTITUTION_WEBSITE', 'https://www.uho.edu.cu')
INSTITUTION_LOGO = os.getenv('INSTITUTION_LOGO', 'static/img/logo.png')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
PUBLIC_TRACKING_URL = os.getenv('PUBLIC_TRACKING_URL', f"{FRONTEND_URL.rstrip('/')}/tracking")


# ============================================
# LOGGING
# ============================================
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'django.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'errors.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO' if DEBUG else 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['error_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ============================================
# CELERY HARDENING (producción)
# ============================================
CELERY_TASK_ACKS_LATE = env_bool('CELERY_TASK_ACKS_LATE', True)
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '600'))  # 10 min
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', '540'))  # 9 min
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_DEFAULT_RETRY_DELAY = 60
CELERY_TASK_MAX_RETRIES = 3


# ============================================
# SENTRY (monitoreo de errores, opcional)
# ============================================
SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.celery import CeleryIntegration
        from sentry_sdk.integrations.logging import LoggingIntegration
        import logging as _logging

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(),
                CeleryIntegration(),
                LoggingIntegration(level=_logging.INFO, event_level=_logging.ERROR),
            ],
            traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.05')),
            send_default_pii=False,
            environment=os.getenv('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development'),
            release=os.getenv('SENTRY_RELEASE'),
        )
    except ImportError:
        # sentry-sdk no instalado; ignorar silenciosamente
        pass
