"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde archivo .env
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path)
else:
    # Si no existe .env, intentar cargar desde la raíz del proyecto backend
    load_dotenv(BASE_DIR.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Obtener SECRET_KEY de variables de entorno, con fallback para desarrollo
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-@e2&yg!lk#5aj&yvs-&%%-%@=t90rvn)+y@u*6bdebh7a^et))'  # Fallback solo para desarrollo
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG debe ser False en producción
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Dominio del sitio
DOMAIN = os.getenv('DOMAIN', '127.0.0.1:8000')

# Hosts permitidos - separados por comas en .env
ALLOWED_HOSTS_STR = os.getenv('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]

import sys

# Agregar la carpeta 'apps' al PYTHONPATH
sys.path.append(os.path.join(BASE_DIR, 'apps'))


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    'apps.platform',
    'apps.internal',
    'apps.labs',
    'apps.secretary_doc',
    'apps.notifications',
    #'apps.atention',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', '60'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', '7'))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS Settings - Configurable desde variables de entorno
CORS_ALLOWED_ORIGINS_STR = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173'
)
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in CORS_ALLOWED_ORIGINS_STR.split(',') if origin.strip()
]

CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True').lower() == 'true'
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Solo en desarrollo

# Spectacular Settings (API Documentation)
SPECTACULAR_SETTINGS = {
    'TITLE': 'TUho API - Sistema Integral Universitario',
    'DESCRIPTION': '''
    ## 🎓 API para la aplicación TUho - Sistema Integral de Gestión Universitaria
    
    ### 📋 Funcionalidades Principales
    
    Esta API proporciona endpoints organizados para:
    
    #### 🔐 **Autenticación y Seguridad**
    - Registro y activación de cuentas
    - Login/Logout con JWT
    - Gestión de tokens y sesiones
    - Recuperación de contraseñas
    
    #### 👥 **Gestión de Usuarios**
    - Administración de usuarios del sistema
    - Perfiles y información personal
    - Roles y permisos
    
    #### 📢 **Comunicación**
    - Sistema de notificaciones internas
    - Publicación de noticias y anuncios
    - Configuración de correos electrónicos
    
    #### 🏛️ **Servicios Ciudadanos**
    - Atención a la población
    - Solicitudes y consultas
    - Seguimiento de trámites
    
    #### 🎓 **Servicios Académicos**
    - Trámites de secretaría docente
    - Certificados y documentos
    - Gestión estudiantil
    
    #### 🏢 **Procedimientos Internos**
    - Gestión de huéspedes
    - Servicios de alimentación
    - Transporte institucional
    - Mantenimiento y reparaciones
    
    ---
    
    ### 🚀 **Guía de Inicio Rápido**
    
    #### 1️⃣ **Autenticación**
    ```bash
    # Iniciar sesión
    POST /api/v1/auth/login/
    {
        "username": "tu_usuario",
        "password": "tu_contraseña"
    }
    ```
    
    #### 2️⃣ **Usar Token**
    ```
    Authorization: Bearer <tu_token_jwt>
    ```
    
    #### 3️⃣ **Probar Endpoints**
    Usa el botón "Authorize" arriba para configurar tu token y probar los endpoints.
    
    ---
    
    ### 📊 **Códigos de Respuesta**
    - `200` ✅ Éxito
    - `201` ✅ Creado
    - `400` ❌ Error en datos
    - `401` 🔒 No autorizado
    - `403` 🚫 Sin permisos
    - `404` 🔍 No encontrado
    - `500` 💥 Error servidor
    
    ### 📖 **Documentación Adicional**
    - **ReDoc**: [http://127.0.0.1:8000/api/redoc/](http://127.0.0.1:8000/api/redoc/) - Vista completa
    - **Schema JSON**: [http://127.0.0.1:8000/api/schema/](http://127.0.0.1:8000/api/schema/) - Esquema OpenAPI
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {
        'name': 'Equipo de Desarrollo TUho',
        'email': 'secretariadocenteuho@gmail.com',
        'url': 'https://www.uho.edu.cu'
    },
    'LICENSE': {
        'name': 'Uso Interno - Universidad de Holguín',
        'url': 'https://www.uho.edu.cu'
    },
    'EXTERNAL_DOCS': {
        'description': 'Documentación completa en ReDoc',
        'url': 'http://127.0.0.1:8000/api/redoc/'
    },
    'SERVERS': [
        {
            'url': 'http://127.0.0.1:8000',
            'description': '🛠️ Servidor de Desarrollo Local'
        },
        {
            'url': 'https://api.tuho.uho.edu.cu',
            'description': '🌐 Servidor de Producción (Futuro)'
        }
    ],
    'TAGS': [
        {
            'name': '🔐 Autenticación',
            'description': '''
            **Gestión de acceso y seguridad**
            
            Endpoints para:
            - 🚪 Login/Logout
            - 📝 Registro de usuarios
            - 🔄 Renovación de tokens
            - ✅ Validación de cuentas
            - 🔑 Recuperación de contraseñas
            - 👤 Información de perfil
            '''
        },
        {
            'name': '👥 Usuarios',
            'description': '''
            **Administración de usuarios del sistema**
            
            Funcionalidades:
            - 📋 Listado y búsqueda de usuarios
            - ➕ Creación de nuevos usuarios
            - ✏️ Edición de información personal
            - 🗑️ Eliminación de cuentas
            - 🛡️ Gestión de roles y permisos
            
            **⚠️ Acceso restringido a administradores**
            '''
        },
        {
            'name': '🔔 Notificaciones',
            'description': '''
            **Sistema de notificaciones internas**
            
            Características:
            - 📬 Envío de notificaciones personalizadas
            - 📖 Marcado de leído/no leído
            - 🎯 Notificaciones dirigidas
            - ⏰ Historial temporal
            - 🔍 Filtros y búsqueda
            '''
        },
        {
            'name': '🏛️ Atención a la Población',
            'description': '''
            **Servicios de atención ciudadana**
            
            Incluye:
            - 📝 Solicitudes ciudadanas
            - 📋 Seguimiento de casos
            - 💬 Respuestas oficiales
            - 📊 Estados de tramitación
            - 🗂️ Historial de solicitudes
            '''
        },
        {
            'name': '📰 Plataforma - Noticias',
            'description': '''
            **Gestión de contenido informativo**
            
            Funciones:
            - 📰 Publicación de noticias
            - 📅 Programación de contenido
            - 🖼️ Gestión multimedia
            - 👁️ Control de visibilidad
            - 📈 Métricas de visualización
            '''
        },
        {
            'name': '✉️ Plataforma - Email',
            'description': '''
            **Configuración del sistema de correos**
            
            Administración de:
            - ⚙️ Configuración SMTP
            - 📧 Plantillas de email
            - 🔐 Credenciales de servidor
            - 📊 Logs de envío
            
            **🔒 Solo administradores**
            '''
        },
        {
            'name': '📊 Plataforma - Estados',
            'description': '''
            **Gestión de estados de trámites**
            
            Control de:
            - 🏷️ Definición de estados
            - 🔄 Flujos de trabajo
            - 📈 Seguimiento de progreso
            - 🎨 Personalización visual
            '''
        },
        {
            'name': '🎓 Secretaría Docente',
            'description': '''
            **Servicios académicos y estudiantiles**
            
            Trámites disponibles:
            - 📜 Certificados académicos
            - 📋 Constancias de estudio
            - 🎯 Solicitudes especiales
            - 📊 Historial académico
            - ⚡ Trámites urgentes
            
            **👨‍🎓 Estudiantes ven solo los suyos**
            '''
        },
        {
            'name': '🏨 Procedimientos - Huéspedes',
            'description': '''
            **Gestión de visitantes y huéspedes**
            
            Servicios:
            - 📝 Registro de huéspedes
            - 🏠 Asignación de alojamiento
            - 📅 Control de estadías
            - 💰 Gestión de pagos
            - 📊 Reportes de ocupación
            '''
        },
        {
            'name': '🍽️ Procedimientos - Alimentación',
            'description': '''
            **Servicios de comedor y alimentación**
            
            Gestión de:
            - 📅 Días de alimentación
            - 🍽️ Menús y dietas
            - 👥 Solicitudes de comida
            - 💳 Pagos y descuentos
            - 📈 Estadísticas de consumo
            '''
        },
        {
            'name': '🏢 Procedimientos - Estructura',
            'description': '''
            **Organización interna institucional**
            
            Administración de:
            - 🏛️ Departamentos
            - 📍 Áreas funcionales
            - 👥 Asignación de personal
            - 📊 Jerarquías organizacionales
            - 📋 Responsabilidades
            '''
        },
        {
            'name': '🚗 Procedimientos - Transporte',
            'description': '''
            **Gestión de transporte institucional**
            
            Servicios:
            - 🚌 Solicitudes de transporte
            - 📅 Programación de viajes
            - 🛣️ Rutas y destinos
            - 👨‍✈️ Asignación de conductores
            - ⛽ Control de combustible
            '''
        },
        {
            'name': '🔧 Procedimientos - Mantenimiento',
            'description': '''
            **Sistema de mantenimiento y reparaciones**
            
            Funcionalidades:
            - 🔨 Solicitudes de reparación
            - ⚡ Niveles de prioridad
            - 👷 Asignación de técnicos
            - 📊 Seguimiento de trabajos
            - 💰 Control de costos
            '''
        },
        {
            'name': '🗂️ Estructura - Áreas',
            'description': '''
            **Gestión de áreas básicas del sistema**
            
            Administración de:
            - 📍 Definición de áreas
            - 📝 Descripciones funcionales
            - 🔗 Relaciones jerárquicas
            
            **🔒 Solo administradores**
            '''
        }
    ],
        'COMPONENT_SPLIT_REQUEST': False,
    'SORT_OPERATIONS': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'defaultModelRendering': 'model',
        'displayRequestDuration': True,
        'docExpansion': 'none',
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tryItOutEnabled': True
    },
    'REDOC_UI_SETTINGS': {
        'nativeScrollbars': False,
        'theme': {
            'colors': {
                'primary': {
                    'main': '#1976d2'
                }
            },
            'typography': {
                'fontSize': '14px',
                'lineHeight': '1.5em',
                'code': {
                    'fontSize': '13px'
                },
                'headings': {
                    'fontFamily': 'Montserrat, sans-serif'
                }
            }
        }
    }
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates","templates/"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'notificaciones.context.notificacionesContext',
                'config.context.groups_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Base de Datos postgreSQL
'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'TUho',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST':'127.0.0.1',
        'DATABASE_PORT':'5432',
    }
}'''


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Cuba'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # Directorio donde se recopilan los archivos estáticos
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'Login'


# Email Config - Usar variables de entorno para credenciales sensibles
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'secretariadocenteuho@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'wxeq mujn uogo e lv v')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

ALLOWED_REDIRECT_URLS = ['mailto://']

AUTH_USER_MODEL = 'platform.User'

