# Generated by Django 4.2.27 on 2026-01-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform", "0002_procedure"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedingDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Fecha del día de alimentación", verbose_name="Fecha"
                    ),
                ),
                (
                    "breakfast",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad de desayunos",
                        verbose_name="Desayunos",
                    ),
                ),
                (
                    "lunch",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad de almuerzos",
                        verbose_name="Almuerzos",
                    ),
                ),
                (
                    "dinner",
                    models.IntegerField(
                        default=0, help_text="Cantidad de cenas", verbose_name="Cenas"
                    ),
                ),
                (
                    "snack",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad de meriendas",
                        verbose_name="Meriendas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Día de Alimentación",
                "verbose_name_plural": "Días de Alimentación",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "MASCULINO"), ("F", "FEMENINO")], max_length=1
                    ),
                ),
                ("identification", models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="MaintancePriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del nivel de prioridad",
                        max_length=50,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prioridad de Mantenimiento",
                "verbose_name_plural": "Prioridades de Mantenimiento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaintanceProcedureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del tipo de mantenimiento",
                        max_length=50,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Procedimiento de Mantenimiento",
                "verbose_name_plural": "Tipos de Procedimientos de Mantenimiento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransportProcedureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del tipo de transporte",
                        max_length=50,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Procedimiento de Transporte",
                "verbose_name_plural": "Tipos de Procedimientos de Transporte",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransportProcedure",
            fields=[
                (
                    "procedure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="platform.procedure",
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(
                        help_text="Fecha y hora de salida",
                        verbose_name="Hora de salida",
                    ),
                ),
                (
                    "return_time",
                    models.DateTimeField(
                        help_text="Fecha y hora de regreso",
                        verbose_name="Hora de regreso",
                    ),
                ),
                (
                    "departure_place",
                    models.CharField(
                        help_text="Lugar de salida del transporte",
                        max_length=150,
                        verbose_name="Lugar de salida",
                    ),
                ),
                (
                    "return_place",
                    models.CharField(
                        help_text="Lugar de regreso del transporte",
                        max_length=150,
                        verbose_name="Lugar de regreso",
                    ),
                ),
                (
                    "passengers",
                    models.IntegerField(
                        help_text="Número de personas a transportar",
                        verbose_name="Cantidad de pasajeros",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada de la solicitud",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        blank=True,
                        help_text="Placa del vehículo asignado",
                        max_length=10,
                        null=True,
                        verbose_name="Placa del vehículo",
                    ),
                ),
                (
                    "round_trip",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si es un viaje de ida y vuelta",
                        verbose_name="Viaje redondo",
                    ),
                ),
                (
                    "procedure_type",
                    models.ForeignKey(
                        help_text="Tipo de procedimiento de transporte",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_procedures",
                        to="internal.transportproceduretype",
                        verbose_name="Tipo de transporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Transporte",
                "verbose_name_plural": "Solicitudes de Transporte",
                "ordering": ["-created_at"],
            },
            bases=("platform.procedure",),
        ),
        migrations.CreateModel(
            name="MaintanceProcedure",
            fields=[
                (
                    "procedure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="platform.procedure",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada del problema o mantenimiento requerido",
                        verbose_name="Descripción del problema",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Fotografía del problema o área a mantener",
                        null=True,
                        upload_to="maintenance/images/",
                        verbose_name="Fotografía",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        help_text="Nivel de prioridad del mantenimiento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_procedures",
                        to="internal.maintancepriority",
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "procedure_type",
                    models.ForeignKey(
                        help_text="Tipo de procedimiento de mantenimiento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_procedures",
                        to="internal.maintanceproceduretype",
                        verbose_name="Tipo de mantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Mantenimiento",
                "verbose_name_plural": "Solicitudes de Mantenimiento",
                "ordering": ["-created_at"],
            },
            bases=("platform.procedure",),
        ),
        migrations.CreateModel(
            name="FeedingProcedure",
            fields=[
                (
                    "procedure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="platform.procedure",
                    ),
                ),
                (
                    "feeding_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurante Especializado"),
                            ("HOTELITO", "Hotelito de posgrado de la UHO"),
                        ],
                        help_text="Tipo de servicio de alimentación solicitado",
                        max_length=20,
                        verbose_name="Tipo de alimentación",
                    ),
                ),
                (
                    "start_day",
                    models.DateField(
                        help_text="Fecha de inicio del servicio",
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_day",
                    models.DateField(
                        help_text="Fecha de fin del servicio",
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada de la solicitud",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Número de personas a alimentar",
                        verbose_name="Cantidad de personas",
                    ),
                ),
                (
                    "feeding_days",
                    models.ManyToManyField(
                        help_text="Días específicos de alimentación",
                        related_name="feeding_procedures",
                        to="internal.feedingdays",
                        verbose_name="Días de alimentación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Alimentación",
                "verbose_name_plural": "Solicitudes de Alimentación",
                "ordering": ["-created_at"],
            },
            bases=("platform.procedure",),
        ),
        migrations.CreateModel(
            name="AccommodationProcedure",
            fields=[
                (
                    "procedure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="platform.procedure",
                    ),
                ),
                (
                    "accommodation_type",
                    models.CharField(
                        choices=[
                            ("HOTEL", "Instalaciones Hoteleras"),
                            ("POSGRADO", "Hotelito de posgrado de la UHO"),
                        ],
                        help_text="Tipo de alojamiento solicitado",
                        max_length=20,
                        verbose_name="Tipo de alojamiento",
                    ),
                ),
                (
                    "start_day",
                    models.DateField(
                        help_text="Fecha de inicio del alojamiento",
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_day",
                    models.DateField(
                        help_text="Fecha de fin del alojamiento",
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada de la solicitud",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "feeding_days",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Días en los que se solicita alimentación",
                        related_name="accommodation_procedures",
                        to="internal.feedingdays",
                        verbose_name="Días de alimentación",
                    ),
                ),
                (
                    "guests",
                    models.ManyToManyField(
                        help_text="Huéspedes incluidos en el alojamiento",
                        related_name="accommodation_procedures",
                        to="internal.guest",
                        verbose_name="Huéspedes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Alojamiento",
                "verbose_name_plural": "Solicitudes de Alojamiento",
                "ordering": ["-created_at"],
            },
            bases=("platform.procedure",),
        ),
    ]
