# Generated by Django 4.2.29 on 2026-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingdays',
            name='date',
            field=models.DateField(db_index=True, help_text='Fecha del día de alimentación', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='identification',
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
