# Generated by Django 4.2.27 on 2026-01-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform", "0002_procedure"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se creó el registro",
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de la última modificación",
                        verbose_name="Última modificación",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("INACTIVE", "Inactivo"),
                            ("PENDING", "Pendiente"),
                            ("COMPLETED", "Completado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="ACTIVE",
                        help_text="Estado actual del registro",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el registro está activo en el sistema",
                        verbose_name="Está activo",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INFO", "Información"),
                            ("WARNING", "Advertencia"),
                            ("ERROR", "Error"),
                            ("SUCCESS", "Éxito"),
                            ("SYSTEM", "Sistema"),
                            ("ACADEMIC", "Académico"),
                            ("PROCEDURE", "Trámite"),
                            ("MAINTENANCE", "Mantenimiento"),
                            ("URGENT", "Urgente"),
                        ],
                        default="INFO",
                        help_text="Categoría que define el tipo de notificación",
                        max_length=20,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        default="MEDIUM",
                        help_text="Nivel de prioridad de la notificación",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "asunto",
                    models.CharField(
                        help_text="Título o asunto de la notificación",
                        max_length=255,
                        verbose_name="Asunto",
                    ),
                ),
                (
                    "cuerpo",
                    models.TextField(
                        help_text="Contenido completo de la notificación",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "visto",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la notificación ha sido leída por el destinatario",
                        verbose_name="Leído",
                    ),
                ),
                (
                    "fecha_visto",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se leyó la notificación",
                        null=True,
                        verbose_name="Fecha de lectura",
                    ),
                ),
                (
                    "url_accion",
                    models.URLField(
                        blank=True,
                        help_text="URL opcional a la que redirigir cuando se hace clic en la notificación",
                        null=True,
                        verbose_name="URL de acción",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono a mostrar (ej: 'fa-bell', 'info-circle')",
                        max_length=50,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "expira_en",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha después de la cual la notificación se considera obsoleta",
                        null=True,
                        verbose_name="Fecha de expiración",
                    ),
                ),
                (
                    "datos_adicionales",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional en formato JSON",
                        verbose_name="Datos adicionales",
                    ),
                ),
                (
                    "de",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que envió la notificación (puede ser automático)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones_enviadas",
                        to="platform.user",
                        verbose_name="Remitente",
                    ),
                ),
                (
                    "para",
                    models.ForeignKey(
                        help_text="Usuario que recibirá la notificación",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="platform.user",
                        verbose_name="Destinatario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["para", "visto"], name="notificatio_para_id_7b1629_idx"
                    ),
                    models.Index(
                        fields=["tipo", "prioridad"], name="notificatio_tipo_b58e0a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_f8f3c4_idx"
                    ),
                    models.Index(
                        fields=["expira_en"], name="notificatio_expira__b31bc7_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="notificacion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("asunto__isnull", False), models.Q(("asunto", ""), _negated=True)
                ),
                name="notificacion_asunto_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificacion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("cuerpo__isnull", False), models.Q(("cuerpo", ""), _negated=True)
                ),
                name="notificacion_cuerpo_not_empty",
            ),
        ),
    ]
