# Generated by Django 4.2.27 on 2026-01-05 14:06

import apps.platform.models.news
import apps.platform.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Department name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "activation_token",
                    models.CharField(
                        blank=True,
                        help_text="Token utilizado para activar la cuenta del usuario",
                        max_length=255,
                        null=True,
                        validators=[apps.platform.validators.validate_token_activacion],
                        verbose_name="Token de activación",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        help_text="Número de carnet de identidad (11 dígitos)",
                        max_length=11,
                        unique=True,
                        validators=[apps.platform.validators.validate_carnet_identidad],
                        verbose_name="Carnet de identidad",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono (8 dígitos para Cuba)",
                        max_length=15,
                        null=True,
                        validators=[apps.platform.validators.validate_telefono_cuba],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Dirección completa de residencia",
                        max_length=500,
                        null=True,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de nacimiento del usuario",
                        null=True,
                        verbose_name="Fecha de nacimiento",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("ESTUDIANTE", "Estudiante"),
                            ("PROFESOR", "Profesor"),
                            ("TRABAJADOR", "Trabajador"),
                            ("EXTERNO", "Externo"),
                        ],
                        default="ESTUDIANTE",
                        help_text="Categoría del usuario en el sistema universitario",
                        max_length=20,
                        verbose_name="Tipo de usuario",
                    ),
                ),
                (
                    "workplace",
                    models.CharField(
                        blank=True,
                        help_text="Institución o departamento donde trabaja/estudia",
                        max_length=200,
                        null=True,
                        verbose_name="Centro de trabajo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el email ha sido verificado",
                        verbose_name="Email verificado",
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el teléfono ha sido verificado",
                        verbose_name="Teléfono verificado",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="platform_user_groups",
                        related_query_name="platform_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="platform_user_permissions",
                        related_query_name="platform_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se creó el registro",
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de la última modificación",
                        verbose_name="Última modificación",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("INACTIVE", "Inactivo"),
                            ("PENDING", "Pendiente"),
                            ("COMPLETED", "Completado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="ACTIVE",
                        help_text="Estado actual del registro",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el registro está activo en el sistema",
                        verbose_name="Está activo",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="News title (maximum 255 characters)",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Friendly URL automatically generated from title",
                        max_length=255,
                        unique=True,
                        verbose_name="Friendly URL",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("ACADEMIC", "Académica"),
                            ("MANAGEMENT", "Administrativa"),
                            ("STUDENT", "Estudiantil"),
                            ("CULTURAL", "Cultural"),
                            ("SPORTS", "Deportiva"),
                            ("RESEARCH", "Investigación"),
                            ("EXTENSION", "Extensión Universitaria"),
                        ],
                        default="GENERAL",
                        help_text="News category",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "header_image",
                    models.ImageField(
                        blank=True,
                        help_text="Main news image (optional)",
                        null=True,
                        upload_to=apps.platform.models.news.get_news_upload_path,
                        validators=[apps.platform.validators.validate_file_size],
                        verbose_name="Header image",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Brief news summary (maximum 300 characters)",
                        max_length=300,
                        null=True,
                        verbose_name="Summary",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Full news content", verbose_name="Content"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the news is published",
                        verbose_name="Published",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled date to publish the news",
                        null=True,
                        verbose_name="Publication date",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the news should appear as featured",
                        verbose_name="Featured",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags to facilitate searches",
                        max_length=255,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the news",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_news",
                        to="platform.user",
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-publication_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Area name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="platform.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "db_table": "areas",
                "ordering": ["department", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["id_card"], name="platform_us_id_card_d48018_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="platform_us_email_f3b986_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="platform_us_user_ty_3cd48d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_staff"], name="platform_us_is_acti_937d58_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("id_card",), name="unique_carnet_identidad"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("id_card__isnull", False), models.Q(("id_card", ""), _negated=True)
                ),
                name="carnet_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["is_published", "publication_date", "featured"],
                name="platform_ne_is_publ_eb061b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["category", "is_published"],
                name="platform_ne_categor_b5d454_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(fields=["slug"], name="platform_ne_slug_d6cd7c_idx"),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["author"], name="platform_ne_author__a70d6c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="news",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("title__isnull", False), models.Q(("title", ""), _negated=True)
                ),
                name="news_title_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="news",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("body__isnull", False), models.Q(("body", ""), _negated=True)
                ),
                name="news_body_not_empty",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="area",
            unique_together={("name", "department")},
        ),
    ]
