# Generated by Django 4.2.27 on 2026-01-05 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "numero_seguimiento",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Número único de seguimiento para el trámite",
                        unique=True,
                        verbose_name="Número de seguimiento",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único del trámite",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID del trámite",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADO", "Enviado"),
                            ("EN_PROCESO", "En proceso"),
                            ("REQUIERE_INFO", "Requiere información"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="BORRADOR",
                        help_text="Estado actual del trámite",
                        max_length=20,
                        verbose_name="Estado del trámite",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones o comentarios adicionales",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha límite para completar el trámite",
                        null=True,
                        verbose_name="Fecha límite",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que solicita el trámite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="platform.user",
                        verbose_name="Usuario solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trámite",
                "verbose_name_plural": "Trámites",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["state", "created_at"],
                        name="platform_pr_state_ffdd26_idx",
                    ),
                    models.Index(
                        fields=["user", "state"], name="platform_pr_user_id_70736f_idx"
                    ),
                    models.Index(
                        fields=["deadline"], name="platform_pr_deadlin_2200ee_idx"
                    ),
                ],
            },
        ),
    ]
