# Generated by Django 4.2.27 on 2026-02-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ESTUDIANTE", "Estudiante"),
                    ("PROFESOR", "Profesor"),
                    ("TRABAJADOR", "Trabajador"),
                    ("EXTERNO", "Externo"),
                    ("ADMIN", "Admin"),
                ],
                default="ESTUDIANTE",
                help_text="Categoría del usuario en el sistema universitario",
                max_length=20,
                verbose_name="Tipo de usuario",
            ),
        ),
    ]
