# Generated by Django 4.2.29 on 2026-03-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('PROFESOR', 'Profesor'), ('TRABAJADOR', 'Trabajador'), ('EXTERNO', 'Externo'), ('SECRETARIA_DOCENTE', 'Secretaría Docente'), ('ADMIN', 'Admin')], default='EXTERNO', help_text='Categoría del usuario en el sistema universitario', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
