# Generated by Django 4.2.29 on 2026-04-01 11:08

from django.db import migrations, models


def convert_null_summary_to_empty(apps, schema_editor):
    News = apps.get_model('platform', 'News')
    News.objects.filter(summary__isnull=True).update(summary='')


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.RunPython(convert_null_summary_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, default='', help_text='Brief news summary (maximum 300 characters)', max_length=300, verbose_name='Summary'),
        ),
    ]
