# Generated by Django 4.2.29 on 2026-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0007_fix_news_summary_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('PROFESOR', 'Profesor'), ('TRABAJADOR', 'Trabajador'), ('EXTERNO', 'Externo'), ('SECRETARIA_DOCENTE', 'Secretaría Docente'), ('ADMIN', 'Admin'), ('GESTOR_INTERNO', 'Gestor de Trámites Internos'), ('GESTOR_TRAMITES', 'Gestor de Trámites'), ('GESTOR_RESERVAS', 'Gestor de Reservas')], default='EXTERNO', help_text='Categoría del usuario en el sistema universitario', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
