# Generated by Django 4.2.30 on 2026-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0008_add_gestor_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='observation',
            field=models.TextField(blank=True, help_text='Observaciones o comentarios adicionales. Cuando el estado es RECHAZADO, este campo debe contener el motivo del rechazo.', null=True, verbose_name='Observaciones'),
        ),
    ]
