# Generated by Django 4.2.30 on 2026-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0009_alter_procedure_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que expira el token de activación (24h por defecto)', null=True, verbose_name='Expiración del token de activación'),
        ),
    ]
