# Generated by Django 4.2.30 on 2026-05-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0009_consolidate_roles'),
        ('platform', '0010_user_activation_token_expires_at'),
    ]

    operations = [
    ]
