# Generated by Django 4.2.30 on 2026-04-16 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('state_change', 'Cambio de estado'), ('login', 'Inicio de sesión'), ('login_failed', 'Login fallido'), ('logout', 'Cierre de sesión'), ('password_reset', 'Restablecimiento de contraseña'), ('permission_change', 'Cambio de permisos'), ('user_activation', 'Activación de usuario'), ('user_deactivation', 'Desactivación de usuario'), ('approve', 'Aprobación'), ('reject', 'Rechazo'), ('cancel', 'Cancelación'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('export', 'Exportación'), ('document_generated', 'Documento generado'), ('other', 'Otro')], max_length=32, verbose_name='Acción')),
                ('resource_type', models.CharField(blank=True, help_text='Ej: labs.LocalReservation, platform.User', max_length=100, verbose_name='Tipo de recurso')),
                ('resource_id', models.CharField(blank=True, max_length=64, verbose_name='ID del recurso')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional (diff, estados, context)', verbose_name='Metadatos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la acción (null si anónimo/sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Entrada de auditoría',
                'verbose_name_plural': 'Bitácora de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx')],
            },
        ),
    ]
