# Generated by Django 4.2.30 on 2026-04-16 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Universidad de Holguín', max_length=200)),
                ('institution_short_name', models.CharField(default='UHo', max_length=50)),
                ('institution_address', models.CharField(blank=True, max_length=300)),
                ('institution_website', models.URLField(blank=True)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('reservation_min_minutes', models.PositiveIntegerField(default=30, help_text='Duración mínima (minutos) de una reserva')),
                ('reservation_max_minutes', models.PositiveIntegerField(default=480, help_text='Duración máxima (minutos) de una reserva')),
                ('reservation_open_hour', models.PositiveSmallIntegerField(default=7, help_text='Hora de apertura para reservas (0-23)')),
                ('reservation_close_hour', models.PositiveSmallIntegerField(default=21, help_text='Hora de cierre para reservas (0-23)')),
                ('reservation_advance_days', models.PositiveSmallIntegerField(default=90, help_text='Máximo de días en el futuro para reservar')),
                ('module_internal_enabled', models.BooleanField(default=True)),
                ('module_secretary_enabled', models.BooleanField(default=True)),
                ('module_labs_enabled', models.BooleanField(default=True)),
                ('module_news_enabled', models.BooleanField(default=True)),
                ('signature_enabled', models.BooleanField(default=False)),
                ('qr_verification_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]
