# Generated by Django 4.2.30 on 2026-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_runtime', '0004_consolidate_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapconfig',
            name='group_to_role_map',
            field=models.JSONField(blank=True, default=dict, help_text='Diccionario {"<grupo>": "<user_type>"}. Para LDAP la clave es el DN completo; para HTTP API es el nombre del rol/grupo devuelto por el endpoint. Ej. LDAP: {"cn=gestores_internos,ou=groups,dc=uho,dc=edu,dc=cu": "GESTOR_INTERNO"}. Ej. HTTP: {"gestor_secretaria": "GESTOR_SECRETARIA", "usuario": "USUARIO"}.'),
        ),
    ]
