# Generated by Django 4.2.27 on 2026-01-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform", "0002_procedure"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabsProcedure",
            fields=[
                (
                    "procedure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="platform.procedure",
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        help_text="Laboratorio solicitado",
                        max_length=200,
                        verbose_name="Nombre del laboratorio",
                    ),
                ),
                (
                    "equipment",
                    models.TextField(
                        help_text="Descripción del equipamiento requerido",
                        verbose_name="Equipamiento necesario",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Cuándo se requiere el laboratorio",
                        verbose_name="Fecha y hora de inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="Hasta cuándo se necesita el laboratorio",
                        verbose_name="Fecha y hora de fin",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="Para qué se necesita el laboratorio",
                        verbose_name="Propósito de la solicitud",
                    ),
                ),
                (
                    "expected_attendees",
                    models.PositiveIntegerField(
                        help_text="Número estimado de participantes",
                        verbose_name="Personas esperadas",
                    ),
                ),
                (
                    "responsible_name",
                    models.CharField(
                        help_text="Persona responsable de la actividad",
                        max_length=200,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "responsible_phone",
                    models.CharField(
                        help_text="Contacto del responsable",
                        max_length=20,
                        verbose_name="Teléfono del responsable",
                    ),
                ),
                (
                    "responsible_email",
                    models.EmailField(
                        help_text="Correo del responsable",
                        max_length=254,
                        verbose_name="Email del responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Laboratorio",
                "verbose_name_plural": "Solicitudes de Laboratorio",
                "ordering": ["-created_at"],
            },
            bases=("platform.procedure",),
        ),
    ]
