# Generated by Django 4.2.27 on 2026-01-09 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0003_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID del local",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del local",
                        max_length=200,
                        verbose_name="Nombre del local",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único identificador (ej: AULA-101, LAB-A)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código del local",
                    ),
                ),
                (
                    "local_type",
                    models.CharField(
                        choices=[
                            ("AULA", "Aula"),
                            ("LABORATORIO", "Laboratorio"),
                            ("AUDITORIO", "Auditorio"),
                            ("SALA_REUNIONES", "Sala de reuniones"),
                            ("BIBLIOTECA", "Biblioteca"),
                            ("GIMNASIO", "Gimnasio"),
                            ("CAFETERIA", "Cafetería"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de local",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Número máximo de personas", verbose_name="Capacidad"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción general del local y sus características",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="locals/images/",
                        verbose_name="Imagen del local",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el local está disponible para reservas",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si las reservas requieren aprobación previa",
                        verbose_name="Requiere aprobación",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Local",
                "verbose_name_plural": "Locales",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LocalReservation",
            fields=[
                (
                    "procedure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="platform.procedure",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Inicio de la reserva",
                        verbose_name="Fecha y hora de inicio",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Fin de la reserva",
                        verbose_name="Fecha y hora de fin",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("CLASE", "Clase académica"),
                            ("EXAMEN", "Examen"),
                            ("REUNION", "Reunión"),
                            ("EVENTO", "Evento"),
                            ("TALLER", "Taller"),
                            ("CONFERENCIA", "Conferencia"),
                            ("ESTUDIO", "Estudio grupal"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Propósito de la reserva",
                    ),
                ),
                (
                    "purpose_detail",
                    models.TextField(
                        help_text="Descripción detallada de la actividad a realizar",
                        verbose_name="Detalle del propósito",
                    ),
                ),
                (
                    "expected_attendees",
                    models.PositiveIntegerField(
                        help_text="Número estimado de personas que asistirán",
                        verbose_name="Asistentes esperados",
                    ),
                ),
                (
                    "responsible_name",
                    models.CharField(
                        help_text="Persona responsable del evento/actividad",
                        max_length=200,
                        verbose_name="Nombre del responsable",
                    ),
                ),
                (
                    "responsible_phone",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono del responsable"
                    ),
                ),
                (
                    "responsible_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email del responsable"
                    ),
                ),
                (
                    "setup_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Disposición de mesas, sillas, equipos adicionales, etc.",
                        verbose_name="Requerimientos especiales",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo de rechazo"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Motivo de cancelación"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        help_text="Local a reservar",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="labs.local",
                        verbose_name="Local",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de local",
                "verbose_name_plural": "Reservas de locales",
                "ordering": ["-start_time"],
            },
            bases=("platform.procedure",),
        ),
        migrations.CreateModel(
            name="ReservationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Tipo de acción realizada (creación, edición, aprobación, etc.)",
                        max_length=50,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Información adicional sobre el cambio",
                        verbose_name="Detalles",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="labs.localreservation",
                        verbose_name="Reserva",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que realizó la acción",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de reserva",
                "verbose_name_plural": "Historiales de reservas",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="LabsProcedure",
        ),
        migrations.AddIndex(
            model_name="local",
            index=models.Index(
                fields=["is_active", "local_type"], name="labs_local_is_acti_49df55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="local",
            index=models.Index(fields=["code"], name="labs_local_code_6e1f1b_idx"),
        ),
        migrations.AddIndex(
            model_name="reservationhistory",
            index=models.Index(
                fields=["reservation", "-timestamp"],
                name="labs_reserv_reserva_e13a86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="localreservation",
            index=models.Index(
                fields=["local", "start_time", "end_time"],
                name="labs_localr_local_i_77a461_idx",
            ),
        ),
    ]
