# Generated by Django 4.2.30 on 2026-04-16 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0002_local_localreservation_reservationhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('COMPUTING', 'Cómputo'), ('FURNITURE', 'Mobiliario'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamiento',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text='Cada cuántos días/semanas/meses')),
                ('weekdays', models.CharField(blank=True, help_text='Lista separada por coma de días de la semana (0=lunes...6=domingo).', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.CharField(max_length=20)),
                ('purpose_detail', models.TextField()),
                ('expected_attendees', models.PositiveIntegerField()),
                ('responsible_name', models.CharField(max_length=200)),
                ('responsible_phone', models.CharField(max_length=20)),
                ('responsible_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='labs.local')),
            ],
            options={
                'verbose_name': 'Serie de reservas',
                'verbose_name_plural': 'Series de reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEquipmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.equipment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requests', to='labs.localreservation')),
            ],
            options={
                'verbose_name': 'Equipamiento solicitado',
                'verbose_name_plural': 'Equipamiento solicitado',
            },
        ),
        migrations.CreateModel(
            name='ReservationCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='labs.localreservation')),
            ],
            options={
                'verbose_name': 'Check-in de reserva',
                'verbose_name_plural': 'Check-ins de reservas',
            },
        ),
        migrations.CreateModel(
            name='LocalEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('operational', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='labs.equipment')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='labs.local')),
            ],
            options={
                'verbose_name': 'Inventario por local',
                'verbose_name_plural': 'Inventarios por local',
                'unique_together': {('local', 'equipment')},
            },
        ),
    ]
