# Generated by Django 5.0.2 on 2025-05-16 13:08

import backend.apps.plataforma.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alter_noticias_imagen_cabecera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='Noticias/16-05-2025/', validators=[backend.apps.plataforma.models.models.validate_file_extension]),
        ),
    ]
