# Generated by Django 4.2.30 on 2026-04-16 14:20

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(help_text='Ej: labs.LocalReservation, internal.FeedingProcedure', max_length=100, verbose_name='Tipo de recurso origen')),
                ('resource_id', models.CharField(max_length=64, verbose_name='ID del recurso origen')),
                ('doc_type', models.CharField(choices=[('procedure', 'Constancia de trámite'), ('reservation', 'Confirmación de reserva'), ('certificate', 'Certificado académico'), ('other', 'Otro')], default='procedure', max_length=20)),
                ('verification_code', models.CharField(db_index=True, default=apps.documents.models._gen_verification_code, help_text='Código único para verificar la autenticidad del documento vía QR', max_length=32, unique=True, verbose_name='Código de verificación')),
                ('file', models.FileField(upload_to='documents/official/%Y/%m/', verbose_name='Archivo PDF')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira en')),
                ('revoked', models.BooleanField(default=False, verbose_name='Revocado')),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to=settings.AUTH_USER_MODEL, verbose_name='Emitido para')),
            ],
            options={
                'verbose_name': 'Documento oficial',
                'verbose_name_plural': 'Documentos oficiales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='documents_o_resourc_565400_idx'), models.Index(fields=['issued_to', '-created_at'], name='documents_o_issued__4e6e19_idx')],
            },
        ),
    ]
