# Generated by Django 4.2.27 on 2026-01-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform", "0002_procedure"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretaryDocProcedure",
            fields=[
                (
                    "procedure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="platform.procedure",
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        choices=[("PREGRADO", "Pregrado"), ("POSGRADO", "Posgrado")],
                        help_text="Programa de pregrado o posgrado",
                        max_length=20,
                        verbose_name="Tipo de estudio",
                    ),
                ),
                (
                    "career",
                    models.CharField(
                        help_text="Carrera o programa académico",
                        max_length=150,
                        verbose_name="Carrera",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="Año de estudio", max_length=10, verbose_name="Año"
                    ),
                ),
                (
                    "academic_program",
                    models.CharField(
                        help_text="Nombre del programa académico",
                        max_length=250,
                        verbose_name="Programa académico",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="Tipo de documento solicitado",
                        max_length=100,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[("ESTATAL", "Estatal"), ("NO_ESTATAL", "No Estatal")],
                        default="ESTATAL",
                        help_text="Tipo de interés (estatal/no estatal)",
                        max_length=20,
                        verbose_name="Interés",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Nombre completo del solicitante",
                        max_length=300,
                        verbose_name="Nombre completo",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        help_text="Número de carné de identidad",
                        max_length=15,
                        verbose_name="Carné de identidad",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email del solicitante",
                        max_length=254,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Teléfono de contacto",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True,
                        help_text="Archivo de soporte del trámite",
                        null=True,
                        upload_to="secretary_doc/documents/",
                        verbose_name="Archivo del documento",
                    ),
                ),
                (
                    "registry_volume",
                    models.CharField(
                        blank=True,
                        help_text="Tomo del registro",
                        max_length=10,
                        verbose_name="Tomo",
                    ),
                ),
                (
                    "registry_folio",
                    models.CharField(
                        blank=True,
                        help_text="Folio del registro",
                        max_length=10,
                        verbose_name="Folio",
                    ),
                ),
                (
                    "registry_number",
                    models.CharField(
                        blank=True,
                        help_text="Número del registro",
                        max_length=10,
                        verbose_name="Número",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Secretaría Docente",
                "verbose_name_plural": "Solicitudes de Secretaría Docente",
                "ordering": ["-created_at"],
            },
            bases=("platform.procedure",),
        ),
    ]
