# Generated by Django 4.2.27 on 2026-01-09 21:05

import apps.secretary_doc.models.documento
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("secretary_doc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("solicitud", "Solicitud"),
                            ("identidad", "Documento de Identidad"),
                            ("titulo", "Título Académico"),
                            ("certificado", "Certificado de Notas"),
                            ("pago", "Comprobante de Pago"),
                            ("otro", "Otro Documento"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        help_text="Subir archivo del documento",
                        upload_to=apps.secretary_doc.models.documento.documento_upload_path,
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "nombre_original",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Nombre original del archivo",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de subida"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Cualquier observación adicional sobre este documento",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="SeguimientoTramite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del evento"
                    ),
                ),
                (
                    "tipo_cambio",
                    models.CharField(
                        choices=[
                            ("creacion", "Creación del trámite"),
                            ("cambio_estado", "Cambio de estado"),
                            ("asignacion", "Asignación de funcionario"),
                            ("comentario", "Comentario"),
                            ("documento_agregado", "Documento agregado"),
                            ("documento_eliminado", "Documento eliminado"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de cambio",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Estado anterior",
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nuevo estado",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Detalle de los cambios realizados",
                        verbose_name="Descripción del cambio",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de trámite",
                "verbose_name_plural": "Seguimientos de trámites",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AlterModelOptions(
            name="secretarydocprocedure",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Trámite de Secretaría Docente",
                "verbose_name_plural": "Trámites de Secretaría Docente",
            },
        ),
        migrations.AddField(
            model_name="secretarydocprocedure",
            name="created_by",
            field=models.ForeignKey(
                help_text="Usuario que creó el trámite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_secretary_procedures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="secretarydocprocedure",
            name="folio",
            field=models.CharField(
                blank=True,
                help_text="Folio del registro",
                max_length=10,
                verbose_name="Folio",
            ),
        ),
        migrations.AddField(
            model_name="secretarydocprocedure",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="Número del registro",
                max_length=10,
                verbose_name="Número",
            ),
        ),
        migrations.AddField(
            model_name="secretarydocprocedure",
            name="updated_by",
            field=models.ForeignKey(
                help_text="Último usuario que actualizó el trámite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_secretary_procedures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="secretarydocprocedure",
            name="visibility_type",
            field=models.CharField(
                choices=[("NACIONAL", "Nacional"), ("INTERNACIONAL", "Internacional")],
                default="NACIONAL",
                help_text="Visibilidad nacional o internacional",
                max_length=20,
                verbose_name="Tipo de visibilidad",
            ),
        ),
        migrations.AlterField(
            model_name="secretarydocprocedure",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="Archivo de soporte del trámite",
                null=True,
                upload_to="secretary_doc/documents/%Y/%m/%d/",
                verbose_name="Archivo del documento",
            ),
        ),
        migrations.AddIndex(
            model_name="secretarydocprocedure",
            index=models.Index(
                fields=["study_type", "career"], name="secretary_d_study_t_ccbdf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="secretarydocprocedure",
            index=models.Index(
                fields=["id_card"], name="secretary_d_id_card_5bcb62_idx"
            ),
        ),
        migrations.AddField(
            model_name="seguimientotramite",
            name="tramite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seguimientos",
                to="secretary_doc.secretarydocprocedure",
                verbose_name="Trámite",
            ),
        ),
        migrations.AddField(
            model_name="seguimientotramite",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seguimientos_realizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que realizó el cambio",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="subido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_subidos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Subido por",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="tramite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="secretary_doc.secretarydocprocedure",
                verbose_name="Trámite asociado",
            ),
        ),
        migrations.AddIndex(
            model_name="seguimientotramite",
            index=models.Index(
                fields=["tramite", "fecha"], name="idx_seg_tramite_fecha"
            ),
        ),
        migrations.AddIndex(
            model_name="seguimientotramite",
            index=models.Index(fields=["tipo_cambio"], name="idx_seg_tipo_cambio"),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(fields=["tramite", "tipo"], name="idx_doc_tramite_tipo"),
        ),
    ]
