# Generated by Django 5.0.2 on 2025-10-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0012_department_area_transportprocedure_round_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationprocedure',
            name='feeding_days',
            field=models.ManyToManyField(blank=True, to='internal_procedures.feedingdays'),
        ),
    ]
